### ISSUE TITLE
github.com/agl/ed25519 unmaintained

### ISSUE THREAD

**Issue by sudhagarc** [crossle/libsignal-protocol-go#1]
Above dependency is unmaintained. As per the README in the ed25519 repository:
--8<--
This repository is unmaintained. Please see [x/crypto/ed25519](https://godoc.org/golang.org/x/crypto/ed25519) for a maintained version.

Before trying to recover a previous version from git, note that I left [a one-bit leak](https://github.com/agl/ed25519/issues/27) in the Elligator code in for years because I'm literally not looking at the PRs. Uncared for code is not a foundation to build upon.
--8<--

Any plans to use the x/crypto/ed25519 instead of github/agl/ed25519?

**Comment by oz** [comment]
CMIAW, but it looks like [x/crypto/ed25519 uses 64 bytes](https://github.com/golang/crypto/blob/4b2356b1ed79e6be3deca3737a3db3d132d2847a/ed25519/ed25519.go#L35) for private ED25519 keys, so it can't simpy swapped because the signal protocol [uses 32 bytes](https://github.com/signalapp/libsignal-protocol-c/blob/4a137eaf4eb4421949e2e1dde9f11ec7bc07b88f/src/curve.c#L15).

**Comment by sudhagarc** [comment]
@oz [Fork of github.com/agl/ed25519](https://github.com/DavidMinarsch/ed25519/blob/master/ed25519.go#L20) also defines private key size as 64 bytes. 

I could be wrong, it looks like second half of 32 bytes is used to store public key.

**Comment by crossle** [comment]
The x/crypto/ed25519 can't import internal package golang.org/x/crypto/ed25519/internal/edwards25519, I think to fork it to the package is a good choice

**Comment by sudhagarc** [comment]
Yes, we cannot directly use internal packages. If functions in internal source is required, we could try check with the maintainer (or, submit a PR) and see whether that request can be entertained? That way, there is no less dependency to maintain/worry about.

**Comment by tulir** [comment]
In case anyone is interested, I updated my fork to use [filippo.io/edwards25519](https://github.com/FiloSottile/edwards25519) and the stdlib crypto/ed25519: https://github.com/tulir/libsignal-protocol-go/blob/main/ecc/SignCurve25519.go

**Comment by crossle** [comment]
> In case anyone is interested, I updated my fork to use [filippo.io/edwards25519](https://github.com/FiloSottile/edwards25519) and the stdlib crypto/ed25519: https://github.com/tulir/libsignal-protocol-go/blob/main/ecc/SignCurve25519.go

Cool, DONE d98386470dcd8e5131cb74aa93db02a7044b754b
